INSERT INTO USERS (ID, USERNAME, EMAIL, PASSWORD, ROLE, BALANCE) VALUES (0, 'admin', 'admin@gmail.com', 'admin', 'ADMIN', 0);
INSERT INTO USERS (ID, USERNAME, EMAIL, PASSWORD, ROLE, BALANCE) VALUES (1, 'slim', 'sn@gmail.com', 'slim', 'USER', 1000);
--INSERT INTO BETS (ISACTIVE, WINNER, STAKE, WINNABLESTAKE) VALUES (FALSE, FALSE, 200, 300);
INSERT INTO MATCHES (HOME, AWAY, IS_ACTIVE, HOME_SCORE, AWAY_SCORE, HT_HOME_SCORE, HT_AWAY_SCORE) VALUES ('Man U', 'Chelsea', TRUE, 3, 2, 1, 1);
INSERT INTO MATCHES (HOME, AWAY, IS_ACTIVE, HOME_SCORE, AWAY_SCORE, HT_HOME_SCORE, HT_AWAY_SCORE) VALUES ('Brighton', 'Liverpool', TRUE, 2, 2, 0, 0);

INSERT INTO EVENTS (HOME_ODDS, DRAW_ODDS, AWAY_ODDS, IS_ACTIVE, TYPE, MATCHES_ID) VALUES (2, 3, 2, TRUE, 'WINNER', 1);
--INSERT INTO ISSUES(ID,VERSION,DESCRIPTION,LOCATION,STATUS, TIMESTAMP) VALUES (0,0,'projektor elromlott','123','ADDED',CURRENT_TIMESTAMP())