INSERT INTO USERS (ID, USERNAME, EMAIL, PASSWORD, ROLE, BALANCE) VALUES (0, 'admin', 'admin@gmail.com', 'admin', 'ADMIN', 0);
--INSERT INTO EVENTS (HOMEODDS, DRAWODDS, AWAYODDS) VALUES (2, 3, 2);
--INSERT INTO BETS (ISACTIVE, WINNER, STAKE, WINNABLESTAKE) VALUES (FALSE, FALSE, 200, 300);
--INSERT INTO MATCHES (HOME, AWAY, ISACTIVE) VALUES ('Man U', 'Chelsea', TRUE);

--INSERT INTO ISSUES(ID,VERSION,DESCRIPTION,LOCATION,STATUS, TIMESTAMP) VALUES (0,0,'projektor elromlott','123','ADDED',CURRENT_TIMESTAMP())